"""Create the first unified application administrator on the local identity service.

Uses only localhost and credentials generated by prepare.py. Does not reset an
existing account. The generated password is saved in .env, never printed.
"""
import json
import os
from pathlib import Path
import secrets
from urllib.request import Request, urlopen
from urllib.parse import urlencode

ROOT = Path(__file__).resolve().parent


def main():
    env_path = ROOT / '.env'
    env = dict(line.split('=', 1) for line in env_path.read_text().splitlines() if line and not line.startswith('#'))
    base = env['KEYCLOAK_HOSTNAME'].rstrip('/')
    if base != 'http://localhost:8180':
        raise SystemExit('此初始化脚本只用于本机服务；生产请在 Keycloak 控制台创建管理员')
    request = Request(base + '/realms/master/protocol/openid-connect/token',
        data=urlencode({'grant_type': 'password', 'client_id': 'admin-cli', 'username': env['KEYCLOAK_ADMIN'], 'password': env['KEYCLOAK_ADMIN_PASSWORD']}).encode(),
        headers={'Content-Type': 'application/x-www-form-urlencoded'})
    with urlopen(request, timeout=20) as response:
        token = json.load(response)['access_token']
    def api(path, data=None, method=None):
        req = Request(base + '/admin/realms/jack' + path,
            data=json.dumps(data).encode() if data is not None else None,
            headers={'Authorization': 'Bearer ' + token, 'Content-Type': 'application/json'}, method=method)
        with urlopen(req, timeout=20) as resp:
            content = resp.read()
            return json.loads(content) if content else None
    # A second local frontend can verify SSO without interrupting the existing :3000 app.
    web_client = api('/clients?clientId=knowledge-web')[0]
    web_client['redirectUris'] = list(dict.fromkeys(web_client['redirectUris'] + ['http://localhost:3300/*']))
    web_client['webOrigins'] = list(dict.fromkeys(web_client['webOrigins'] + ['http://localhost:3300']))
    web_client['attributes']['post.logout.redirect.uris'] = 'http://localhost:3000/*##http://localhost:3300/*'
    api('/clients/' + web_client['id'], web_client, 'PUT')
    scopes = api('/client-scopes')
    basic = next(scope for scope in scopes if scope['name'] == 'basic')
    for client_id in ('jack-portal', 'knowledge-web'):
        client = api('/clients?clientId=' + client_id)[0]
        api('/clients/' + client['id'] + '/default-client-scopes/' + basic['id'], method='PUT')
    username = 'jack-admin'
    existing = api('/users?' + urlencode({'username': username, 'exact': 'true'}))
    if existing:
        print('统一管理员已存在，保留现有密码及权限。')
        return
    password = 'Jk9!' + secrets.token_urlsafe(24)
    # Save first so a later transient HTTP failure never loses the generated secret.
    if 'JACK_ADMIN_PASSWORD' in env:
        password = env['JACK_ADMIN_PASSWORD']
    else:
        with env_path.open('a') as output:
            output.write(f'\nJACK_ADMIN_USERNAME={username}\nJACK_ADMIN_PASSWORD={password}\n')
        os.chmod(env_path, 0o600)
    api('/users', {'username': username, 'enabled': True, 'firstName': '杰克', 'lastName': '管理员',
        'email': 'jack-admin@localhost.invalid', 'emailVerified': False,
        'credentials': [{'type': 'password', 'value': password, 'temporary': False}]}, 'POST')
    user = api('/users?' + urlencode({'username': username, 'exact': 'true'}))[0]
    for client_id, names in [('kb-api', ['super_admin']), ('realm-management', ['manage-users', 'view-users', 'query-users', 'view-clients', 'query-groups'])]:
        client = api('/clients?clientId=' + client_id)[0]
        roles = api('/clients/' + client['id'] + '/roles')
        chosen = [role for role in roles if role['name'] in names]
        if len(chosen) != len(names):
            raise RuntimeError('未找到所需角色，请到控制台补齐，脚本不会扩大角色范围')
        api('/users/' + user['id'] + '/role-mappings/clients/' + client['id'], chosen, 'POST')
    print('已创建本机统一管理员 jack-admin；密码保存在 deploy/keycloak/.env。')


if __name__ == '__main__':
    main()
